services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - '3000:3000'
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - '80:80'
    depends_on:
      - api
    restart: unless-stopped
